import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Layouts } from "@/components/layouts";
import { Footer } from "@/components/fragments/Footer";


const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Euro-Kontrakan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="euro-logo.png" />
      </head>
      <body className={poppins.className}>
        <Layouts>
          {children}
        </Layouts>
        <Footer/>
      </body>
    </html>
  );
}
